
package com.mycompany.login1;

import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author drako
 */
public class ConsultarCurso extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarCurso
     */
    public ConsultarCurso() {
        initComponents();
        ActualizarTabla();
}
    private void ActualizarTabla(){
        
        DefaultTableModel data = new DefaultTableModel (new String[]{"id","NombreCurso","Seccion","FechaInicio","FechaFin","HoraInicio","HoraFin", "Profesor"}, Login1.cursos.size());
        jTable1.setModel(data);
        
        int row=0;
        
        for(Curso cl : Login1.cursos){
            jTable1.setValueAt(cl.id, row, 0);
            jTable1.setValueAt(cl.NombreCurso, row, 1);
            jTable1.setValueAt(cl.Seccion, row, 2);
            jTable1.setValueAt(cl.FechaInicio, row, 3);
            jTable1.setValueAt(cl.FechaFin, row, 4);
            jTable1.setValueAt(cl.HoraInicio, row, 5);
            jTable1.setValueAt(cl.HoraFin, row, 6);
            jTable1.setValueAt(cl.Profesor, row, 7);
            row++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("cursoJson");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton1)
                        .addGap(49, 49, 49)
                        .addComponent(jButton2)
                        .addGap(50, 50, 50)
                        .addComponent(jButton3)
                        .addGap(58, 58, 58)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        CursoEditar CE = new CursoEditar(jTable1.getSelectedRow());
        CE.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        ActualizarTabla();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

                                               

        
        JFileChooser archivo = new JFileChooser();
        int retorno = archivo.showDialog(this, "Cargar");
        if (retorno == JFileChooser.APPROVE_OPTION) {
            JSONParser jp = new JSONParser();
            try {
                FileReader r = new FileReader(archivo.getSelectedFile().toPath().toString());
                Object obj = jp.parse(r);

                JSONArray cursosList = (JSONArray) obj;

                for (Object c : cursosList) {
                    
                    JSONObject curso = (JSONObject) c;

                    String codigoCurso = String.valueOf(curso.get("id"));
                    String nombreCurso = (String) curso.get("nombre");
                    String seccion = (String) curso.get("seccion");
                    String fechaInicio = (String) curso.get("fecha_inicio");
                    String fechaFin = (String) curso.get("fecha_fin");
                    String horaInicio = (String) curso.get("hora_inicio");
                    String horaFin = (String) curso.get("hora_fin");
                    String profesor = (String) curso.get("profesor");
                    
                    Curso nuevoCurso = new Curso();
                    
                    nuevoCurso.NombreCurso = nombreCurso;
                    nuevoCurso.id = codigoCurso;
                    nuevoCurso.Seccion = seccion;
                    nuevoCurso.FechaInicio = fechaInicio;
                    nuevoCurso.FechaFin = fechaFin;
                    nuevoCurso.Profesor = profesor;
                    nuevoCurso.HoraInicio=  horaInicio;
                    nuevoCurso.HoraFin = horaFin;

                    
                    Login1.cursos.add(nuevoCurso);
                    
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
           
            ActualizarTabla();
            JOptionPane.showMessageDialog(null, "Archivo Cargado Exitosamente");
        }

    
    }//GEN-LAST:event_jButton4ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
